routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HorarioController;
use App\Http\Controllers\PacienteController;
use App\Http\Controllers\TelefonoController;
use App\Http\Controllers\CitaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('horarios', HorarioController::class);

Route::resource('pacientes', PacienteController::class);

Route::resource('telefonos', TelefonoController::class);

Route::resource('citas', CitaController::class);

app/Models/Paciente.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Paciente extends Model
{
    use HasFactory;
    protected $table = 'pacientes';
    protected $primaryKey = 'id';
    public $timestamps = false;
    protected $fillable = [
        'id',
        'nombres_paciente',
        'email_paciente',
        'ciudad_paciente',
        'telefono_id ',
    ];

    public function telefono() {
        return $this->belongsTo(Telefono::class);
    }

    public function citas() {
        return $this->hasMany(Cita::class);
    }
}

app/Http/Controllers/PacienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Paciente;

class PacienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pacientes = Paciente::select("*")
                    ->with('telefono')
                    ->with('citas')
                    ->get();
        return view('pacientes.index', compact('pacientes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pacientes/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div align="center">
            <h2>Agregar Nuevo Horario</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('horarios.index') }}"> Regresar</a>
        </div>

        <form action="{{ route('horarios.store') }}" method="POST">
            @csrf

            <div class="row">
                <div>
                    <div class="form-group">
                        <strong>Día Atención:</strong>
                        <input type="date" name="dia_horario_atencion" class="form-control"
                            placeholder="Ingrese el día de atención" value="{{ old('dia_horario_atencion') }}" required>
                        @error('dia_horario_atencion')
                            <p class="error-message">{{ $message }}</p>
                        @enderror
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Hora Inicio de Atención:</strong>
                        <input type="time" name="inicio_horario_atencion" class="form-control"
                            value="{{ old('inicio_horario_atencion') }}" required>
                        @error('inicio_horario_atencion')
                            <p class="error-message">{{ $message }}</p>
                        @enderror
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Hora Fin de Atención:</strong>
                        <input type="time" name="fin_horario_atencion" class="form-control"
                            value="{{ old('fin_horario_atencion') }}" required>
                        @error('fin_horario_atencion')
                            <p class="error-message">{{ $message }}</p>
                        @enderror
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Tiene discapacidad:</strong>
                        <input type="tel" name="texto_horario_atencion" class="form-control"
                        value="{{ old('texto_horario_atencion') }}" pattern="[+][0-5]{3}[0-9]{9}">
                        @error('texto_horario_atencion')
                            <p class="error-message">{{ $message }}</p>
                        @enderror
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/pacientes/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Horario de Atención</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('horarios.index') }}"> Regresar</a>
            </div>
        </div>
    </div>
    <form action="{{ route('horarios.update',$horario->id) }}" method="POST">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Día Atención:</strong>
                    <input type="date" name="dia_horario_atencion" class="form-control" value="{{ $horario->dia_horario_atencion }}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Hora Inicio Atención:</strong>
                    <input type="time" name="inicio_horario_atencion" class="form-control" value="{{ $horario->inicio_horario_atencion }}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Hora Fin Atención:</strong>
                    <input type="time" name="fin_horario_atencion" class="form-control" value="{{ $horario->fin_horario_atencion }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>
@endsection

resources/views/pacientes/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <br />
        <h1 align="center">REPORTE DE HORARIOS DE ATENCIÓN</h1>
        <div>
            <a class="btn btn-success" href="{{ route('pacientes.create') }}">Crear</a>
        </div>
        <br />
        @if (Session::get('success'))
            <div class="alert alert-success">
                <p>{{ Session::get('success') }}</p>
            </div>
        @endif
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Nombres Paciente</th>
                <th>Email Paciente</th>
                <th>Ciudad Paciente</th>
                <th>Teléfono Paciente</th>
                <th>Citas</th>
                <th>Acciones</th>
            </tr>
            @foreach ($pacientes as $paciente)
                <tr>
                    <td>{{ $paciente->id }}</td>
                    <td>{{ $paciente->nombres_paciente }}</td>
                    <td>{{ $paciente->email_paciente }}</td>
                    <td>{{ $paciente->ciudad_paciente }}</td>
                    <td>{{ $paciente->telefono->operadora_tel }}</td>
                    <td>
                    @foreach ($paciente->citas as $cita)
                        <p>{{ $cita->fecha_cita }}</p>
                    @endforeach
                    </td>
                </tr>
            @endforeach
        </table>
    </div>
@endsection