routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HorarioController;
use App\Http\Controllers\PacienteController;
use App\Http\Controllers\TelefonoController;
use App\Http\Controllers\CitaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('horarios', HorarioController::class);

Route::resource('pacientes', PacienteController::class);

Route::resource('telefonos', TelefonoController::class);

Route::resource('citas', CitaController::class);

app/Models/Cita.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cita extends Model
{
    use HasFactory;
    protected $table = 'citas';
    protected $primaryKey = 'id';
    public $timestamps = false;
    protected $fillable = [
        'id',
        'fecha_cita',
        'hora_cita',
        'paciente_id',
        'cupon_cita',
    ];

    public function paciente() {
        return $this->belongsTo(Paciente::class, 'paciente_id');
    }

    public function terapias() {
        return $this->belongsToMany(Terapia::class,'citas_has_terapias');
    }
}

app/Http/Controllers/CitaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Cita;
use App\Models\Paciente;
use App\Models\Terapia;
use App\Models\CitashasTerapias;
use Illuminate\Support\Facades\Validator;

class CitaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $citas = Cita::select("*")
            ->with('paciente')
            ->with('terapias')
            ->get();
        
        return view('citas.index', compact('citas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pacientes = Paciente::all();
        $terapias = Terapia::all();
        return view('citas.create', compact('pacientes','terapias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $v = Validator::make($request->all(), [
            'fecha_cita' => 'required',
            'hora_cita' => 'required',
            'paciente_id' => 'required',
        ]);

        if ($v->fails()) {
            return redirect()->back()->withErrors($v->errors())->withInput();
        } else {
            //$cita = Cita::create($request->all());
            $ruta="";
            if($request->hasFile("cupon_cita")){
                $file=$request->file("cupon_cita");
                
                $nombre = "cupon_".time().".".$file->guessExtension();
    
                $ruta = public_path("cupones/".$nombre);
                copy($file, $ruta);
            }

            $cita = new Cita;
            $cita->fecha_cita = $request->fecha_cita;
            $cita->hora_cita = $request->hora_cita;
            $cita->paciente_id = $request->paciente_id;
            $cita->cupon_cita = $nombre;
            $cita->save();

            CitashasTerapias::create(['cita_id'=>$cita->id, 'terapia_id'=>$request->terapia_id]);
            return redirect()->route('citas.index')->with('success', 'Horario creado exitosamente!!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/citas/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div align="center">
            <h2>Agregar Nueva Cita</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('citas.index') }}"> Regresar</a>
        </div>

        <form action="{{ route('citas.store') }}" method="POST" enctype="multipart/form-data">
            @csrf

            <div class="row">
                <div>
                    <div class="form-group">
                        <strong>Fecha de Cita:</strong>
                        <input type="date" name="fecha_cita" class="form-control" value="{{ old('fecha_cita') }}"
                            required>
                        @error('fecha_cita')
                            <p class="error-message">{{ $message }}</p>
                        @enderror
                    </div>
                </div>

                <div>
                    <div class="form-group">
                        <strong>Hora de Cita:</strong>
                        <input type="time" name="hora_cita" class="form-control" value="{{ old('hora_cita') }}" required>
                        @error('hora_cita')
                            <p class="error-message">{{ $message }}</p>
                        @enderror
                    </div>
                </div>
                <div>
                    <div class="form-group">
                        <strong>Pacientes:</strong>
                        <select class="form-select" name="paciente_id" aria-label="Default select example">
                            <option value="undefined" selected="true" disabled>Seleccione un paciente:</option>
                            @foreach ($pacientes as $paciente)
                                <option value={{$paciente->id}}>{{$paciente->nombres_paciente}}
                                </option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div>
                    <div class="form-group">
                        <strong>Terapias:</strong>
                        <select class="form-select" name="terapia_id" aria-label="Default select example">
                            <option value="undefined" selected="true" disabled>Seleccione una terapia:</option>
                            @foreach ($terapias as $terapia)
                                <option value={{$terapia->id}}>{{$terapia->nombre_terapia}}
                                </option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div>
                    <div class="form-group">
                        <strong>Archivo Cupón:</strong>
                        <input type="file" name="cupon_cita" class="form-control">
                      </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/citas/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Horario de Atención</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('horarios.index') }}"> Regresar</a>
            </div>
        </div>
    </div>
    <form action="{{ route('horarios.update',$horario->id) }}" method="POST">
        @csrf
        @method('PUT')
         <div class="row">
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Día Atención:</strong>
                    <input type="date" name="dia_horario_atencion" class="form-control" value="{{ $horario->dia_horario_atencion }}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Hora Inicio Atención:</strong>
                    <input type="time" name="inicio_horario_atencion" class="form-control" value="{{ $horario->inicio_horario_atencion }}">
                </div>
            </div>
            <div class="col-xs-8 col-sm-8 col-md-8" style="margin: 0 auto; float: none;">
                <div class="form-group">
                    <strong>Hora Fin Atención:</strong>
                    <input type="time" name="fin_horario_atencion" class="form-control" value="{{ $horario->fin_horario_atencion }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </div>
    </form>
@endsection

resources/views/citas/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <br />
        <h1 align="center">REPORTE DE CITAS</h1>
        <div>
            <a class="btn btn-success" href="{{ route('citas.create') }}">Crear</a>
        </div>
        <br />
        @if (Session::get('success'))
            <div class="alert alert-success">
                <p>{{ Session::get('success') }}</p>
            </div>
        @endif
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Fecha de Cita</th>
                <th>Hora de Cita</th>
                <th>Paciente</th>
                <th>Terapia</th>
                <th>Acciones</th>
            </tr>
            @foreach ($citas as $cita)
                <tr>
                    <td>{{ $cita->id }}</td>
                    <td>{{ $cita->fecha_cita }}</td>
                    <td>{{ $cita->hora_cita }}</td>
                    <td>{{ $cita->paciente->nombres_paciente }}</td>
                    <td>
                        @foreach ($cita->terapias as $terapia)
                            <p>{{ $terapia->nombre_terapia }}</p>
                        @endforeach
                    </td>
                    @if ($cita->cupon_cita != '')
                        <td><a href="./cupones/{{ $cita->cupon_cita }}" target="blank"><i style="color: red;"
                                    class="fas fa-file-pdf fa-2x"></i></a></td>
                    @else
                        <td></td>
                    @endif
                </tr>
            @endforeach
        </table>
    </div>
@endsection